pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: true
  params: count=countSql

qbs:
  entrypoint:
    base: /api
    auth:
      base: ${qbs.entrypoint.base}/auth
      usernameLogin: ${qbs.entrypoint.auth.base}/login
      mobileLogin: ${qbs.entrypoint.auth.base}/login/mobile
      imageLogin: ${qbs.entrypoint.auth.base}/login/image
      tokenProtect: ${qbs.entrypoint.base}/**
    ignored:
      - ${qbs.entrypoint.auth.base}/**